
import { ProtocolPerson, HallConfig, HallKey } from './types';

export const TURKEY_CITIES = [
  "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir",
  "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli",
  "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari",
  "Hatay", "Isparta", "Mersin", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli", "Kırşehir",
  "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir",
  "Niğde", "Ordu", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat",
  "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman",
  "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce"
];

export const CITY_HALLS: Record<string, HallKey[]> = {
  "Muğla": ['yildiz', 'turkan', 'msku', 'bodrum'],
  // Diğer iller için şimdilik boş veya varsayılan salonlar eklenebilir
};

// YARDIMCI FONKSİYONLAR (Eski koddaki mantığı korur)
const generateOdd = (start: number, end: number) => {
  let seats: any[] = [];
  for (let i = start; i <= end; i += 2) seats.push({ number: i.toString(), type: 'seat' });
  return seats;
};

const generateEven = (start: number, end: number) => {
  let seats: any[] = [];
  if (start > end) {
    for (let i = start; i >= end; i -= 2) seats.push({ number: i.toString(), type: 'seat' });
  } else {
    for (let i = start; i <= end; i += 2) seats.push({ number: i.toString(), type: 'seat' });
  }
  return seats;
};

const generateSeq = (count: number) => {
  let seats: any[] = [];
  for (let i = 1; i <= count; i++) seats.push({ number: i.toString(), type: 'seat' });
  return seats;
};

const generateBlock = (prefix: string, count: number) => {
  let seats: any[] = [];
  for (let i = 1; i <= count; i++) seats.push({ number: prefix + "-" + i, type: 'seat' });
  return seats;
};

const createBodrumRow = (rowName: string, leftCount: number, centerCount: number, rightCount: number) => {
  let s: any[] = [];
  if (leftCount > 0) {
    s.push(...generateBlock("A", leftCount));
    s.push({ type: 'gap', size: 'small' });
  }
  if (centerCount > 0) {
    s.push(...generateBlock("B", centerCount));
    s.push({ type: 'gap', size: 'small' });
  }
  if (rightCount > 0) {
    s.push(...generateBlock("C", rightCount));
  }
  return { row: rowName, seats: s };
};

export const PROTOCOL_DATA: ProtocolPerson[] = [
  {id: 1, sira: 1, u: "VALİ", i: "Dr. İdris AKBIYIK", tg: "gokhanyoldas"},
  {id: 2, sira: 2, u: "Milletvekili", i: "Kadem METE"},
  {id: 3, sira: 3, u: "Milletvekili", i: "Yakup OTGÖZ"},
  {id: 4, sira: 4, u: "Milletvekili", i: "Cumhur UZUN"},
  {id: 5, sira: 5, u: "Milletvekili", i: "Gizem ÖZCAN"},
  {id: 6, sira: 6, u: "Milletvekili", i: "Süreyya ÖNEŞ DERİCİ"},
  {id: 7, sira: 7, u: "Milletvekili", i: "Selçuk ÖZDAĞ"},
  {id: 8, sira: 8, u: "Milletvekili", i: "Metin ERGUN"},
  {id: 9, sira: 9, u: "Güney Deniz Saha Komutanı", i: "Koramiral Rafet OKTAR"},
  {id: 10, sira: 10, u: "Harp Filo Komutanı", i: "Tümamiral Mehmet Baybars KÜÇÜKATAY"},
  {id: 11, sira: 11, u: "Aksaz Deniz Üs Komutanı", i: "Tuğamiral Hamdi ABANOZ"},
  {id: 12, sira: 12, u: "Aksaz Tersanesi Komutanı", i: "Tuğamiral Cemalettin ÇİFTÇİ"},
  {id: 13, sira: 13, u: "16. Ana Jet Üs Komutanı", i: "Hava Pilot Tuğgeneral Yusuf KARUK"},
  {id: 14, sira: 14, u: "Güney Görev Grup Komutanı", i: "Tuğamiral İlyas ERGEL"},
  {id: 15, sira: 15, u: "Lojistik Destek Görev Grup Komutanı", i: "Tuğamiral Lütfü SEZGİN"},
  {id: 16, sira: 16, u: "Büyükşehir Belediye Başkanı", i: "Ahmet ARAS"},
  {id: 17, sira: 17, u: "Cumhuriyet Başsavcısı", i: "Oğuzhan DÖNMEZ"},
  {id: 18, sira: 18, u: "Adli Yargı Adalet Komisyon Başkanı", i: "Ercan ARSLAN"},
  {id: 19, sira: 19, u: "1.İdare Mahkemesi Başkanı", i: "Ali DORU"},
  {id: 20, sira: 20, u: "2.İdare Mahkemesi Başkanı", i: "Levent ÖZALP"},
  {id: 21, sira: 21, u: "3.İdare Mahkemesi Başkanı", i: "Feyzullah ERTAN"},
  {id: 22, sira: 22, u: "4.İdare Mahkemesi Başkanı", i: "Arda KARA"},
  {id: 23, sira: 23, u: "Vergi Mahkemesi Başkanı", i: "Eda EKMEKCİ"},
  {id: 24, sira: 24, u: "Muğla Sıtkı Koçman Üniversitesi Rektörü", i: "Prof. Dr. Turhan KAÇAR"},
  {id: 25, sira: 25, u: "Baro Başkanı", i: "Avukat Levent AKGÜN"},
  {id: 26, sira: 26, u: "Vali Yardımcısı", i: "Halil Serdar CEVHEROĞLU"},
  {id: 27, sira: 27, u: "Vali Yardımcısı", i: "İsmail SOYKAN"},
  {id: 28, sira: 28, u: "Vali Yardımcısı", i: "Hüseyin KARAMEŞE"},
  {id: 29, sira: 29, u: "Vali Yardımcısı", i: "Ali YILMAZ"},
  {id: 30, sira: 30, u: "Vali Yardımcısı", i: "Murat SARI"},
  {id: 31, sira: 31, u: "Vali Yardımcısı", i: "Murat KAHRAMAN"},
  {id: 32, sira: 32, u: "Vali Yardımcısı V.", i: "Mehmet ERİŞ"},
  {id: 33, sira: 33, u: "Bodrum Kaymakamı", i: "Ali SIRMALI"},
  {id: 34, sira: 34, u: "Dalaman Kaymakamı", i: "Mesut YAKUTA"},
  {id: 35, sira: 35, u: "Datça Kaymakamı", i: "Murat ATICI"},
  {id: 36, sira: 36, u: "Fethiye Kaymakamı", i: "Fatih AKKAYA"},
  {id: 37, sira: 37, u: "Kavaklıdere Kaymakamı", i: "Ali ARGAMA"},
  {id: 38, sira: 38, u: "Köyceğiz Kaymakamı", i: "Mert KUMCU"},
  {id: 39, sira: 39, u: "Marmaris Kaymakamı", i: "Nurullah KAYA"},
  {id: 40, sira: 40, u: "Menteşe Kaymakamı", i: "Mehmet ERİŞ"},
  {id: 41, sira: 41, u: "Milas Kaymakamı", i: "Mustafa Ünver BÖKE"},
  {id: 42, sira: 42, u: "Ortaca Kaymakamı", i: "Kenan AKTAŞ"},
  {id: 43, sira: 43, u: "Seydikemer Kaymakamı", i: "Mustafa DİLEKLİ"},
  {id: 44, sira: 44, u: "Ula Kaymakamı", i: "Mehmet Rıdvan DOĞAN"},
  {id: 45, sira: 45, u: "Yatağan Kaymakamı", i: "Turgay İLHAN"},
  {id: 46, sira: 46, u: "İl Emniyet Müdürü", i: "Süleyman KARADENİZ"},
  {id: 47, sira: 47, u: "İl Jandarma Komutanı", i: "Tuğgeneral Adem ŞEN"},
  {id: 48, sira: 48, u: "Sahil Güvenlik Güney Ege Grup Komutanı", i: "S.G. Yarbay Akın COŞKUNLAR"},
  {id: 49, sira: 49, u: "Bodrum Belediye Başkanı", i: "Tamer MANDALİNCİ"},
  {id: 50, sira: 50, u: "Dalaman Belediye Başkanı", i: "Sezer DURMUŞ"},
  {id: 51, sira: 51, u: "Datça Belediye Başkanı", i: "Aytaç KURT"},
  {id: 52, sira: 52, u: "Fethiye Belediye Başkanı", i: "Alim KARACA"},
  {id: 53, sira: 53, u: "Kavaklıdere Belediye Başkanı", i: "Mehmet DEMİR"},
  {id: 54, sira: 54, u: "Köyceğiz Belediye Başkanı", i: "Ali ERDOĞAN"},
  {id: 55, sira: 55, u: "Marmaris Belediye Başkanı", i: "Acar ÜNLÜ"},
  {id: 56, sira: 56, u: "Menteşe Belediye Başkanı", i: "Gonca KÖKSAL ARAS"},
  {id: 57, sira: 57, u: "Milas Belediye Başkanı", i: "Fevzi TOPUZ"},
  {id: 58, sira: 58, u: "Ortaca Belediye Başkanı", i: "Evren TEZCAN"},
  {id: 59, sira: 59, u: "Seydikemer Belediye Başkanı", i: "Bayram Önder AKDENİZLİ"},
  {id: 60, sira: 60, u: "Ula Belediye Başkanı", i: "Mehmet CANER"},
  {id: 61, sira: 61, u: "Yatağan Belediye Başkanı", i: "Mesut GÜNAY"},
  {id: 62, sira: 62, u: "Sıtkı Koçman Üniversitesi Rektör Yardımcısı", i: "Prof. Dr. Deniz ÜLGEN"},
  {id: 63, sira: 63, u: "Sıtkı Koçman Üniversitesi Rektör Yardımcısı", i: "Prof. Dr. Hatice Hicret GÖRGÜLÜ"},
  {id: 64, sira: 64, u: "Sıtkı Koçman Üniversitesi Rektör Yardımcısı", i: "Prof. Dr. Mustafa GÖKÇE"},
  {id: 65, sira: 65, u: "Sıtkı Koçman Üniversitesi Genel Sekreter V.", i: "Prof. Dr. Mehmet AVCI"},
  {id: 66, sira: 66, u: "Bodrum Güzel Sanatlar Fakültesi Dekanı", i: "Prof. Burcu KARABEY"},
  {id: 67, sira: 67, u: "Diş Hekimliği Fakültesi Dekanı", i: "Prof. Dr. Akın ALADAĞ"},
  {id: 68, sira: 68, u: "Edebiyat Fakültesi Dekanı", i: "Prof. Dr. Mustafa GÖKÇE"},
  {id: 69, sira: 69, u: "Eğitim Fakültesi Dekanı", i: "Prof. Dr. Osman Raşit IŞIK"},
  {id: 70, sira: 70, u: "Fen Fakültesi Dekanı", i: "Prof. Dr. Alper TONGUÇ"},
  {id: 71, sira: 71, u: "Fethiye İşletme Fakültesi Dekanı", i: "Prof. Dr. İlknur KOCA"},
  {id: 72, sira: 72, u: "Fethiye Sağlık Bilimleri Fakültesi Dekan V.", i: "Prof. Dr. Ali SÜLÜN"},
  {id: 73, sira: 73, u: "Fethiye Ziraat Fakültesi Dekanı", i: "Prof. Dr. Şaban KORDALI"},
  {id: 74, sira: 74, u: "Hukuk Fakültesi Dekan V.", i: "Prof. Dr. Turhan KAÇAR"},
  {id: 75, sira: 75, u: "İktisadi ve İdari Bilimler Fakültesi Dekanı", i: "Prof. Dr. Hatice Hicret GÖRGÜLÜ"},
  {id: 76, sira: 76, u: "İlahiyat Fakültesi Dekan V.", i: "Prof. Dr. Hammet ARSLAN"},
  {id: 77, sira: 77, u: "Milas Veterinerlik Fakültesi Dekanı", i: "Prof. Dr. Artay YAĞCI"},
  {id: 78, sira: 78, u: "Mimarlık Fakültesi Dekan V.", i: "Prof. Dr. Cengiz KOÇ"},
  {id: 79, sira: 79, u: "Mühendislik Fakültesi Dekanı", i: "Prof. Dr. Deniz ÜLGEN"},
  {id: 80, sira: 80, u: "Sağlık Bilimleri Fakültesi Dekanı", i: "Prof. Dr. Ömer GİDER"},
  {id: 81, sira: 81, u: "Spor Bilimleri Fakültesi Dekanı", i: "Prof. Dr. Özcan SAYGIN"},
  {id: 82, sira: 82, u: "Su Ürünleri Fakültesi Dekanı", i: "Prof. Dr. Ertan ERCAN"},
  {id: 83, sira: 83, u: "Teknoloji Fakültesi Dekanı", i: "Prof. Dr. Mehmet ÇOLAK"},
  {id: 84, sira: 84, u: "Teknik Eğitim Fakültesi Dekan V.", i: "Prof. Dr. Mehmet ÇOLAK"},
  {id: 85, sira: 85, u: "Tıp Fakültesi Dekanı", i: "Prof. Dr. Süleyman Cüneyt KARAKUŞ"},
  {id: 86, sira: 86, u: "Turizm Fakültesi Dekanı", i: "Prof. Dr. Gökhan AYAZLAR"},
  {id: 87, sira: 87, u: "Eğitim Bilimleri Enstitüsü Müdürü", i: "Prof. Dr. Şevki KÖMÜR"},
  {id: 88, sira: 88, u: "Fen Bilimleri Enstitüsü Müdürü", i: "Prof. Dr. Reşat ÜNAL"},
  {id: 89, sira: 89, u: "Sağlık Bilimleri Enstitüsü Müdürü", i: "Prof. Dr. Müesser ÖZCAN"},
  {id: 90, sira: 90, u: "Sosyal Bilimler Enstitüsü Müdürü", i: "Prof. Dr. Muzaffer DEMİR"},
  {id: 91, sira: 91, u: "Dalaman Sivil Havacılık YO Müdürü", i: "Prof. Dr. Aytekin FIRAT"},
  {id: 92, sira: 92, u: "Seydikemer Uygulamalı Bilimler YO Müdür V.", i: "Prof. Dr. Nilsun SARIYER"},
  {id: 93, sira: 93, u: "Yabancı Diller YO Müdürü", i: "Prof. Dr. Murat KEÇİŞ"},
  {id: 94, sira: 94, u: "Bodrum Denizcilik MYO Müdürü", i: "Prof. Dr. Tuncay KULELİ"},
  {id: 95, sira: 95, u: "Dalaman MYO Müdürü", i: "Doç. Dr. Ozan KAYA"},
  {id: 96, sira: 96, u: "Datça Kazım Yılmaz MYO Müdürü", i: "Doç. Dr. Uğur ÇALIŞKAN"},
  {id: 97, sira: 97, u: "Fethiye Ali Sıtkı Mefharet Koçman MYO Müdürü", i: "Doç. Dr. Zeynep Rabiye ARDAHANLIOĞLU"},
  {id: 98, sira: 98, u: "Fethiye Sağlık Hizmetleri MYO Müdürü", i: "Doç. Dr. İsmail UYSAL"},
  {id: 99, sira: 99, u: "Kavaklıdere Şehit Mustafa Alper MYO Müdürü", i: "Dr. Öğr. Üyesi Sultan KINCAL"},
  {id: 100, sira: 100, u: "Köyceğiz MYO Müdürü", i: "Doç. Dr. Hatice ULUSOY"},
  {id: 101, sira: 101, u: "Köyceğiz Sağlık Hizmetleri MYO Müdürü", i: "Dr. Öğr. Üyesi Züleyha SEKİ"},
  {id: 102, sira: 102, u: "Marmaris Turizm MYO Müdürü", i: "Doç. Dr. Zehra TÜRK"},
  {id: 103, sira: 103, u: "Milas MYO Müdürü", i: "Prof. Dr. Hüseyin ÇEKEN"},
  {id: 104, sira: 104, u: "Muğla MYO Müdürü", i: "Öğr. Gör. Dr. Osman Emre ARLI"},
  {id: 105, sira: 105, u: "Muğla Turizm MYO Müdürü", i: "Doç. Dr. Senem YAZICI YILMAZ"},
  {id: 106, sira: 106, u: "Ortaca MYO Müdürü", i: "Doç. Dr. Fatime ERDOĞAN"},
  {id: 107, sira: 107, u: "Sağlık Hizmetleri MYO Müdürü", i: "Prof. Dr. Ali İmran VAİZOĞULLAR"},
  {id: 108, sira: 108, u: "Ula Ali Koçman MYO Müdürü", i: "Prof. Dr. Özgür CEYLAN"},
  {id: 109, sira: 109, u: "Yatağan MYO Müdürü", i: "Doç. Dr. Ahmet Deniz BAŞ"},
  {id: 110, sira: 110, u: "Büyükşehir Belediyesi Genel Sekreteri", i: "Tayfun YILMAZ"},
  {id: 111, sira: 111, u: "Büyükşehir Belediyesi MUSKİ Genel Müdürü", i: "Yılmaz ŞENGÜL"},
  {id: 112, sira: 112, u: "Garnizon Komutanı", i: "Mu. Ütğm. Oğuzhan ÖKER"},
  {id: 113, sira: 113, u: "Cumhuriyet Başsavcı V.", i: "Alicenk DÜZGÜN"},
  {id: 114, sira: 114, u: "1. Ağır Ceza Mahkeme Başkanı", i: "Ercan ARSLAN"},
  {id: 115, sira: 115, u: "1. Ağır Ceza Mahkeme Hakimi", i: "Mine KESKİN KARABAY"},
  {id: 116, sira: 116, u: "1. Ağır Ceza Mahkeme Hakimi", i: "Emrullah ÇOLAK"},
  {id: 117, sira: 117, u: "1. Ağır Ceza Mahkeme Hakimi", i: "Muhammet Emirhan DEMİRTAŞ"},
  {id: 118, sira: 118, u: "1. Ağır Ceza Mahkeme Hakimi", i: "Selvinur SARI"},
  {id: 119, sira: 119, u: "2. Ağır Ceza Mahkeme Başkanı", i: "Uğur SAN"},
  {id: 120, sira: 120, u: "2.Ağır Ceza Mahkeme Hakimi", i: "Zeliha ÇİÇEK"},
  {id: 121, sira: 121, u: "2.Ağır Ceza Mahkeme Hakimi", i: "Zehra Nur GÜLTEKİN"},
  {id: 122, sira: 122, u: "2.Ağır Ceza Mahkeme Hakimi", i: "Ayşe YAVUZ"},
  {id: 123, sira: 123, u: "2.Ağır Ceza Mahkeme Hakimi", i: "Mehmet YILDIRIM"},
  {id: 124, sira: 124, u: "3. Ağır Ceza Mahkeme Başkanı", i: "Mustafa GÜNEŞ"},
  {id: 125, sira: 125, u: "3.Ağır Ceza Mahkeme Hakimi", i: "Sebiha Betül KOÇ"},
  {id: 126, sira: 126, u: "3.Ağır Ceza Mahkeme Hakimi", i: "İsmail KÖKER"},
  {id: 127, sira: 127, u: "3.Ağır Ceza Mahkeme Hakimi", i: "Mahmut ÇAKMAK"},
  {id: 128, sira: 128, u: "1. Asliye Ceza Mahkeme Hakimi", i: "Fatma İÇDEMİR"},
  {id: 129, sira: 129, u: "2. Asliye Ceza Mahkeme Hakimi", i: "Bilal ADIGÜZEL"},
  {id: 130, sira: 130, u: "3. Asliye Ceza Mahkeme Hakimi", i: "Asu SEZER"},
  {id: 131, sira: 131, u: "4. Asliye Ceza Mahkeme Hakimi", i: "Halit İÇDEMİR"},
  {id: 132, sira: 132, u: "5. Asliye Ceza Mahkeme Hakimi", i: "Hamit SARAK"},
  {id: 133, sira: 133, u: "6. Asliye Ceza Mahkeme Hakimi", i: "Hülya DEMİR ARSLAN"},
  {id: 134, sira: 134, u: "İnfaz Hakimi", i: "Yusuf TEK"},
  {id: 135, sira: 135, u: "1. Sulh Ceza Hakimliği", i: "Hakan ERCİYAS"},
  {id: 136, sira: 136, u: "2. Sulh Ceza Hakimliği", i: "Hatice ARSLAN"},
  {id: 137, sira: 137, u: "İcra Ceza Hukuk Mahkemesi Hakimi", i: "Tamer ŞAHİN"},
  {id: 138, sira: 138, u: "Asliye Ticaret Mahkemesi Başkanı", i: "Hayriye SOLAK KARGI"},
  {id: 139, sira: 139, u: "Asliye Ticaret Mahkemesi Hakimi", i: "Demet TEK"},
  {id: 140, sira: 140, u: "Asliye Ticaret Mahkemesi Hakimi", i: "Hatice CAN"},
  {id: 141, sira: 141, u: "Asliye Ticaret Mahkemesi Hakimi", i: "Tuğba ÜNAL"},
  {id: 142, sira: 142, u: "1.Asliye Hukuk Mahkeme Hakimi", i: "Alkan ALTAN"},
  {id: 143, sira: 143, u: "2.Asliye Hukuk Mahkeme Hakimi", i: "Servet ÇOBAN"},
  {id: 144, sira: 144, u: "3.Asliye Hukuk Mahkeme Hakimi", i: "Emre ÜNAL"},
  {id: 145, sira: 145, u: "İş Mahkemesi Hakimi", i: "Tüba AYAN DOĞAN"},
  {id: 146, sira: 146, u: "İş Mahkemesi Hakimi", i: "Yasemen PEKER"},
  {id: 147, sira: 147, u: "1.Aile Mahkemesi Hakimi", i: "Buket DOĞAN"},
  {id: 148, sira: 148, u: "2.Aile Mahkemesi Hakimi", i: "Nur Melda ADIGÜZEL"},
  {id: 149, sira: 149, u: "1.Sulh Hukuk Mahkemesi Hakimi", i: "Yasemin KELEŞ"},
  {id: 150, sira: 150, u: "2.Sulh Hukuk Mahkemesi Hakimi", i: "Tutku SARI"},
  {id: 151, sira: 151, u: "Kadastro Mahkemesi Hakimi", i: "Kerim KARABAY"},
  {id: 152, sira: 152, u: "Hakim", i: "Sümeyye NOĞMAN ÇOLAK"},
  {id: 153, sira: 153, u: "Cumhuriyet Savcısı", i: "Arif ULUSOY"},
  {id: 154, sira: 154, u: "Cumhuriyet Savcısı", i: "Hüseyin KAYIKÇI"},
  {id: 155, sira: 155, u: "Cumhuriyet Savcısı", i: "Nevzat BULUT"},
  {id: 156, sira: 156, u: "Cumhuriyet Savcısı", i: "Beşir ASLAN"},
  {id: 157, sira: 157, u: "Cumhuriyet Savcısı", i: "Fatih GELİŞ"},
  {id: 158, sira: 158, u: "Cumhuriyet Savcısı", i: "Selamettin BAYÇELEBİ"},
  {id: 159, sira: 159, u: "Cumhuriyet Savcısı", i: "Tuğba AKALIN"},
  {id: 160, sira: 160, u: "Cumhuriyet Savcısı", i: "Mehmet İlker DURMAZ"},
  {id: 161, sira: 161, u: "Cumhuriyet Savcısı", i: "Bahtiyar KARGI"},
  {id: 162, sira: 162, u: "Cumhuriyet Savcısı", i: "Yalçın ÖZMEN"},
  {id: 163, sira: 163, u: "Cumhuriyet Savcısı", i: "Hilal KÜÇÜK GÖNÜL"},
  {id: 164, sira: 164, u: "Cumhuriyet Savcısı", i: "Etem AYDIN"},
  {id: 165, sira: 165, u: "Cumhuriyet Savcısı", i: "Hasan ÇETİN"},
  {id: 166, sira: 166, u: "Cumhuriyet Savcısı", i: "Mehmet Şirin KELEŞ"},
  {id: 167, sira: 167, u: "Cumhuriyet Savcısı", i: "Yusuf ÇİÇEK"},
  {id: 168, sira: 168, u: "Cumhuriyet Savcısı", i: "Sevcan ERCİYAS"},
  {id: 169, sira: 169, u: "Cumhuriyet Savcısı", i: "Murat Furkan SAĞLAM"},
  {id: 170, sira: 170, u: "Cumhuriyet Savcısı", i: "Aslı SAĞLAM"},
  {id: 171, sira: 171, u: "Cumhuriyet Savcısı", i: "Mehmet Bestami AY"},
  {id: 172, sira: 172, u: "1.İdare Mahkemesi Hakimi", i: "Muharrem ŞEN"},
  {id: 173, sira: 173, u: "1.İdare Mahkemesi Hakimi", i: "Özlem YALÇINKAYA"},
  {id: 174, sira: 174, u: "1.İdare Mahkemesi Hakimi", i: "Elifnur YAVRUTÜRK"},
  {id: 175, sira: 175, u: "1.İdare Mahkemesi Hakimi", i: "Hasan ÖZGÜL"},
  {id: 176, sira: 176, u: "2.İdare Mahkemesi Hakimi", i: "Özlem ARSLAN"},
  {id: 177, sira: 177, u: "2.İdare Mahkemesi Hakimi", i: "Ali KÖSE"},
  {id: 178, sira: 178, u: "2.İdare Mahkemesi Hakimi", i: "Reşit KULAK"},
  {id: 179, sira: 179, u: "3.İdare Mahkemesi Hakimi", i: "Selahattin UÇMAZ"},
  {id: 180, sira: 180, u: "3.İdare Mahkemesi Hakimi", i: "İbrahim TESADÜF"},
  {id: 181, sira: 181, u: "3.İdare Mahkemesi Hakimi", i: "Mehmet Ali AŞIKOĞLU"},
  {id: 182, sira: 182, u: "4.İdare Mahkemesi Hakimi", i: "Sezgin HATİPOĞLU"},
  {id: 183, sira: 183, u: "4.İdare Mahkemesi Hakimi", i: "Oğuz Han SIR"},
  {id: 184, sira: 184, u: "4.İdare Mahkemesi Hakimi", i: "Volkan EREN"},
  {id: 185, sira: 185, u: "4.İdare Mahkemesi Hakimi", i: "Kübra KARACA KULAK"},
  {id: 186, sira: 186, u: "4.İdare Mahkemesi Hakimi", i: "Zeynep ÖZTEL"},
  {id: 187, sira: 187, u: "Vergi Mahkemesi Hakimi", i: "Pınar KUL"},
  {id: 188, sira: 188, u: "Vergi Mahkemesi Hakimi", i: "Mehmet Serdar SARIOĞLU"},
  {id: 189, sira: 189, u: "AK Parti İl Başkanı", i: "Cengizhan GÜNGÖR"},
  {id: 190, sira: 190, u: "CHP İl Başkanı", i: "Nail KIZIL"},
  {id: 191, sira: 191, u: "MHP İl Başkanı", i: "Burak DEMİREL"},
  {id: 192, sira: 192, u: "İYİ Parti İl Başkanı", i: "Davut Cumhur AKMEŞE"},
  {id: 193, sira: 193, u: "Saadet Partisi İl Başkanı", i: "Cebrail TÜMENCİ"},
  {id: 194, sira: 194, u: "İl Müftüsü", i: "Dr. Rüstem CAN"},
  {id: 195, sira: 195, u: "İletişim Başkanlığı Muğla Bölge Müdür V.", i: "Sezgin SAĞUN"},
  {id: 196, sira: 196, u: "E Tipi Kapalı Ceza İnfaz Kurumu Müdürü", i: "Salih UYSAL"},
  {id: 197, sira: 197, u: "Açık Ceza İnfaz Kurumu Müdürü", i: "Mehmet Ali YILDIRIM"},
  {id: 198, sira: 198, u: "Denetimli Serbestlik Müdürü", i: "Mehmet Korkmaz PEKER"},
  {id: 199, sira: 199, u: "Adli Tıp Şube Müdürü", i: "Dr. Ufuk İLİNGİ"},
  {id: 200, sira: 200, u: "Aile ve Sosyal Hizmetler İl Müdürü", i: "Yakup KÜTÜK"},
  {id: 201, sira: 201, u: "İl Sosyal Yardımlaşma ve Dayanışma Vakfı Müdür V.", i: "İbrahim ERTAŞ"},
  {id: 202, sira: 202, u: "Çalışma ve İş Kurumu İl Müdürü", i: "Zahide ALTINOK"},
  {id: 203, sira: 203, u: "Sosyal Güvenlik Kurumu İl Müdürü", i: "Özkan ARSLAN"},
  {id: 204, sira: 204, u: "Çevre,Şehircilik ve İklim Değişikliği İl Müdürü V.", i: "Yusuf SARIKAYA"},
  {id: 205, sira: 205, u: "Kentsel Dönüşüm Müdür V.", i: "Yusuf SARIKAYA"},
  {id: 206, sira: 206, u: "Meteoroloji 4. Bölge Müdürü", i: "Murat AYVAZOĞLU"},
  {id: 207, sira: 207, u: "Meteoroloji Müdürü", i: "Hasan KAYMAK"},
  {id: 208, sira: 208, u: "Kadastro Müdürü", i: "Hüseyin Onur SARIKAYA"},
  {id: 209, sira: 209, u: "ADM Muğla Bölge Müdürü", i: "Fatih YALÇIN"},
  {id: 210, sira: 210, u: "ADM Bodrum Bölge Müdürü", i: "Mustafa AKDAĞ"},
  {id: 211, sira: 211, u: "Gençlik ve Spor İl Müdür V.", i: "Musa Kazım AÇIKBAŞ"},
  {id: 212, sira: 212, u: "İl Defterdar V.", i: "İlhan AKÇAY"},
  {id: 213, sira: 213, u: "Milli Piyango İdaresi Şube Müdürü", i: "Mehmet Cenger ALPAY"},
  {id: 214, sira: 214, u: "Özel Kalem Müdürü", i: "Ahmet KARAÇALI"},
  {id: 215, sira: 215, u: "İl Basın ve Halkla İlişkiler Müdürü", i: "Ahmet SARAÇ"},
  {id: 216, sira: 216, u: "İl Yazı İşleri Müdürü", i: "Serkan ALTAN"},
  {id: 217, sira: 217, u: "İl İdare Kurulu Müdürü", i: "Arif ÖZDEMİR"},
  {id: 218, sira: 218, u: "İl Planlama ve Koordinasyon Müdürü", i: "Ersel DEDE"},
  {id: 219, sira: 219, u: "İdare ve Denetim Müdürü", i: "Çetin DEDELER"},
  {id: 220, sira: 220, u: "Protokol Şube Müdür V.", i: "Durali DOĞRU"},
  {id: 221, sira: 221, u: "Hukuk İşleri Şube Müdürü", i: "Esma DOĞAN CANDAN"},
  {id: 222, sira: 222, u: "İdari Hizmetler Şube Müdürü", i: "Serkan ŞAHİN"},
  {id: 223, sira: 223, u: "Bilgi İşlem Şube Müdürü", i: "İsmail ÖCAL"},
  {id: 224, sira: 224, u: "İl Nüfus ve Vatandaşlık Müdürü", i: "Utku CANDAN"},
  {id: 225, sira: 225, u: "İl Sosyal Etüt ve Proje Müdürü", i: "Özden İŞLER"},
  {id: 226, sira: 226, u: "İl Sivil Toplumla İlişkiler Müdürü", i: "Murat KAMAL"},
  {id: 227, sira: 227, u: "İl Göç İdaresi Müdürü", i: "Cihad GEZEN"},
  {id: 228, sira: 228, u: "İl Afet ve Acil Durum Müdürü", i: "İshak CİNDİOĞLU"},
  {id: 229, sira: 229, u: "Açık Kapı Şube Müdürü", i: "Zeynep KARASU AKÇA"},
  {id: 230, sira: 230, u: "Yatırım İzleme Müdür V.", i: "Önder SULAR"},
  {id: 231, sira: 231, u: "Doğal Kaynaklar, Ruhsat ve Kültür Varlıkları Müdür V.", i: "Ersel DEDE"},
  {id: 232, sira: 232, u: "İdari ve Mali İşler Müdür V.", i: "Sezai SUDA"},
  {id: 233, sira: 233, u: "Rehberlik ve Denetim Müdür V.", i: "Ahmet ESEN"},
  {id: 234, sira: 234, u: "Strateji ve Koordinasyon Müdür V.", i: "Gülay TEKBIYIK AYTAŞ"},
  {id: 235, sira: 235, u: "Hukuk İşleri Müdürü", i: "Umut GÜLMÜŞ"},
  {id: 236, sira: 236, u: "112 Acil Çağrı Merkezi Müdürü", i: "Kamil KARAKAYA"},
  {id: 237, sira: 237, u: "İl Kültür ve Turizm Müdürü", i: "Hüseyin TOPRAK"},
  {id: 238, sira: 238, u: "Kültür Varlıkları Koruma Bölge Kurulu Müdürü", i: "Lütfi EKİNCİ"},
  {id: 239, sira: 239, u: "İl Milli Eğitim Müdürü", i: "Emre ÇAY"},
  {id: 240, sira: 240, u: "Askerlik Şubesi Başkanı", i: "Per. Kd. Bçvş. Fehmi ARSLAN"},
  {id: 241, sira: 241, u: "İl Sağlık Müdürü", i: "Dr. Eriş BAŞARAN AKÇA"},
  {id: 242, sira: 242, u: "İl Sanayi ve Teknoloji Müdürü", i: "Munise İlkay SARAÇ"},
  {id: 243, sira: 243, u: "KOSGEB Muğla İl Müdürü", i: "Bayram Ali KUKUŞ"},
  {id: 244, sira: 244, u: "Güney Ege Kalkınma Ajansı Genel Sekreteri (GEKA)", i: "Ümit GÜLYAĞI"},
  {id: 245, sira: 245, u: "Türk Standardları Enstitüsü İl Temsilcisi", i: "Yeşim ÇETİN ÇAKMAK"},
  {id: 246, sira: 246, u: "DSİ 21. Bölge Müdürü", i: "Birol ÇINAR"},
  {id: 247, sira: 247, u: "Orman Bölge Müdürü", i: "Mustafa ÜLKÜDÜR"},
  {id: 248, sira: 248, u: "Doğa Koruma ve Milli Parklar 4. Bölge Müdürü", i: "Kerim GENÇOĞLU"},
  {id: 249, sira: 249, u: "Tarım ve Orman İl Müdürü", i: "Seyfettin BAYDAR"},
  {id: 250, sira: 250, u: "Muğla Doğa Koruma ve Milli Parklar Müdür V.", i: "Sinan ÇÖP"},
  {id: 251, sira: 251, u: "DSİ 213. Şube Müdürü", i: "Nurettin KIVRAK"},
  {id: 252, sira: 252, u: "DSİ 214. Şube Müdürü", i: "Kağan ERGEN"},
  {id: 253, sira: 253, u: "Gıda Kontrol Laboratuvar Müdür V.", i: "Abidin ATİLLA"},
  {id: 254, sira: 254, u: "İl Ticaret Müdür V.", i: "Mehmet DEMİRTAŞ"},
  {id: 255, sira: 255, u: "Karayolları 2. Bölge Müdürü", i: "Murat GÖNENLİ"},
  {id: 256, sira: 256, u: "Karayolları 13. Bölge Müdürü", i: "Hasan SARIOĞLAN"},
  {id: 257, sira: 257, u: "PTT 2. Bölge Müdürü Y.", i: "Avni ORUÇLU"},
  {id: 258, sira: 258, u: "Telekom İl Müdürü", i: "Hüseyin ERTEK"},
  {id: 259, sira: 259, u: "Karayolları 26. Şube Şefi", i: "Duru ÖZTOP"},
  {id: 260, sira: 260, u: "Karayolları 131. Şube Şefi", i: "Erkan ERKMEN"},
  {id: 261, sira: 261, u: "Anahtar Parti İl Başkanı", i: "Ömer KIZILKAYA"},
  {id: 262, sira: 262, u: "Anavatan Partisi İl Başkanı", i: "İlyas ALPARSLAN"},
  {id: 263, sira: 263, u: "Bağımsız Türkiye Partisi İl Başkanı", i: "Süreyya KARASAKAL"},
  {id: 264, sira: 264, u: "Büyük Birlik Partisi İl Başkanı", i: "Özkan BOZKURT"},
  {id: 265, sira: 265, u: "Demokrat Parti İl Başkanı", i: "Atınç KOYLU"},
  {id: 266, sira: 266, u: "Demokratik Sol Parti İl Başkanı", i: "Sultan AYNACI"},
  {id: 267, sira: 267, u: "Doğru Yol Partisi İl Başkanı", i: "Hasan PEKDAĞLI"},
  {id: 268, sira: 268, u: "Emek Partisi İl Başkanı", i: "Nuri ALİKOÇ"},
  {id: 269, sira: 269, u: "Gelecek Partisi İl Başkanı", i: "Murat SODRA"},
  {id: 270, sira: 270, u: "Millet Partisi İl Başkanı", i: "Yaşar ORHAN"},
  {id: 271, sira: 271, u: "Sol Parti İl Başkanı", i: "Zekeriya KARGIN"},
  {id: 272, sira: 272, u: "Türkiye Komünist Partisi İl Başkanı", i: "Aydın TURAN"},
  {id: 273, sira: 273, u: "Vatan Partisi (İşçi Partisi) İl Başkanı", i: "Emre AYKIN"},
  {id: 274, sira: 274, u: "Yeniden Refah Partisi İl Başkanı", i: "Fatih Salih Mehmet KOCABIYIK"},
  {id: 275, sira: 275, u: "Zafer Partisi İl Başkanı", i: "Nazmi EYİBİLİR"},
  {id: 276, sira: 276, u: "Ticaret ve Sanayi Odası Başkanı", i: "Bülent KARAKUŞ"},
  {id: 277, sira: 277, u: "Ticaret Borsası Başkanı", i: "Hurşit ÖZTÜRK"},
  {id: 278, sira: 278, u: "Menteşe Ziraat Odası Başkanı", i: "Mehmet BAŞTUĞ"},
  {id: 279, sira: 279, u: "Kam. Oto. ve Şoförler Esnaf Odası Başkanı", i: "Ümit KARATAŞ"},
  {id: 280, sira: 280, u: "Esnaf ve Sanatkarlar Odaları Birliği Başkanı", i: "Şükrü AYYILDIZ"},
  {id: 281, sira: 281, u: "Eczacı Odası Başkanı", i: "Saim KORKMAZ"},
  {id: 282, sira: 282, u: "Tabip Odası Başkanı", i: "Dr. Çetin ERDOLU"},
  {id: 283, sira: 283, u: "Veteriner Hekimler Odası Başkanı", i: "Serkan ALPÖZEN"},
  {id: 284, sira: 284, u: "Serbest Muhasebeci Mali Müşavirler Odası Başkanı", i: "Halil İbrahim SAGUŞ"},
  {id: 285, sira: 285, u: "Yeminli Mali Müşavirler Odası İl Temsilcisi", i: "Mehmet Kubilay ÖZCAN"},
  {id: 286, sira: 286, u: "TMMOB Muğla İl Koordinasyon Kurulu Sekreteri", i: "Coşkun ÇATALKAYA"},
  {id: 287, sira: 287, u: "TMMOB İnşaat Mühendisleri Odası Muğla Şube Başkanı", i: "Levent ÇİMEN"},
  {id: 288, sira: 288, u: "TMMOB Şehir Plancıları Odası Muğla Şube Başkanı", i: "Burak TEKER"},
  {id: 289, sira: 289, u: "TMMOB Ziraat Mühendisleri Odası Muğla Şube Başkanı", i: "Ali ŞİMŞEK"},
  {id: 290, sira: 290, u: "TMMOB Makina Mühendisleri Odası İl Temsilcisi", i: "Mehmet Orçun ÇİĞDEM"},
  {id: 291, sira: 291, u: "TMMOB Maden Mühendisleri Odası İl Temsilcisi", i: "Muammer YARAMIŞ"},
  {id: 292, sira: 292, u: "Mimarlar Odası Muğla Şube Başkanı", i: "Mürsel SELÇUK"},
  {id: 293, sira: 293, u: "Elektrik Mühendisleri Odası Muğla İl Temsilcisi", i: "Onur CEYLAN"},
  {id: 294, sira: 294, u: "Diş Hekimleri Odası Başkanı", i: "Zekeriya Doruk ALP"},
  {id: 295, sira: 295, u: "Orman Mühendisleri Odası İl Temsilcisi", i: "Kazım TURGUT"},
  {id: 296, sira: 296, u: "Muğla Turist Rehberleri Odası Yön.Kur.Bşk.", i: "Özgür AKGÜL"},
  {id: 297, sira: 297, u: "Sıtkı Koçman Vakfı Başkanı", i: "Alan PERESE"},
  {id: 298, sira: 298, u: "Tarım Kredi Kooperatifi Müdürü", i: "Mehmet KARAKAŞ"},
  {id: 299, sira: 299, u: "Esnaf Kefalet Kooperatif Başkanı", i: "Azim ÇETİN"},
  {id: 300, sira: 300, u: "Muğla Emlak Danışmanları Esnaf Odası", i: "Ziya ERCAN"},
  {id: 301, sira: 301, u: "Muğla Optisyen Gözlükçüler Odası", i: "Sinan ÇETİNKAYA"},
  {id: 302, sira: 302, u: "Muğla Yiyecek Mad.Yapanlar ve Satanlar Esnaf Odası Bşk.", i: "Güven AKARKEN"},
  {id: 303, sira: 303, u: "TÜRK-İŞ İl Başkanı", i: "Fatih ERÇELİK"},
  {id: 304, sira: 304, u: "DİSK İl Temsilcisi", i: "Uzay KOCABAŞ"},
  {id: 305, sira: 305, u: "HAK-İŞ Başkanı", i: "Nilüfer KAVASOĞLU"},
  {id: 306, sira: 306, u: "KESK Dönem Sözcüsü", i: "Nilüfer ENGİNSU"},
  {id: 307, sira: 307, u: "MEMUR-SEN Başkanı", i: "Özcan ÇİÇEK"},
  {id: 308, sira: 308, u: "KAMU-SEN Başkanı", i: "Mürsel ÖZATA"},
  {id: 309, sira: 309, u: "TİSK İl Temsilcisi", i: "Nurettin KIVRAK"},
  {id: 310, sira: 310, u: "Kamu Birliği Konfederasyonu İl Başkanı", i: "Zübeyir SARUHAN"},
  {id: 311, sira: 311, u: "Muğla Gazeteciler Cemiyeti Derneği Başkanı", i: "Süleyman AKBULUT"},
  {id: 312, sira: 312, u: "Muğla Büyükşehir Gazeteciler Derneği Başkanı", i: "Cem KAYTAN"},
  {id: 313, sira: 313, u: "Ziraat Bankası Bölge Yöneticisi", i: "Ümit Yaşar ÖREN"},
  {id: 314, sira: 314, u: "Vakıfbank Bölge Müdürü", i: "Ali KARAMIK"},
  {id: 315, sira: 315, u: "Ziraat Bankası Müdürü", i: "Çınar UZUN"},
  {id: 316, sira: 316, u: "Halkbankası Müdürü", i: "Şenay ERDEN"},
  {id: 317, sira: 317, u: "Vakıfbank Müdürü", i: "Çağlar ÖZKAN"},
  {id: 318, sira: 318, u: "Yapı Kredi Bankası Müdürü", i: "Burhanettin NEBİOĞLU"},
  {id: 319, sira: 319, u: "Garanti Bankası Müdürü", i: "Volkan ZARİF"},
  {id: 320, sira: 320, u: "İşbankası Müdürü", i: "Didem BALYER BALABAN"},
  {id: 321, sira: 321, u: "Akbank Müdürü", i: "Yusuf Ali DEMİROK"},
  {id: 322, sira: 322, u: "Türk Ekonomi Bankası Müdürü", i: "Serkan ATAŞ"},
  {id: 323, sira: 323, u: "Şekerbank Müdürü", i: "Ebru HEDİYE DEMİRAL"},
  {id: 324, sira: 324, u: "Finansbank A.Ş. Müdürü", i: "Asuman TÜZÜN"},
  {id: 325, sira: 325, u: "Denizbank Müdürü", i: "Işık Söğüt TANÇ"},
  {id: 326, sira: 326, u: "Türkiye Finans Katılım Bankası Müdürü", i: "Gökhan KOLSUZ"},
  {id: 327, sira: 327, u: "Muğla Verem Savaş Derneği", i: "Dr. Can KİRİŞÇİ"},
  {id: 328, sira: 328, u: "Türk Hava Kurumu Başkanı", i: "Ali COŞKUN"},
  {id: 329, sira: 329, u: "Türk Kızılay Muğla İl Merkezi Başkanı", i: "Şadi PİRCİ"},
  {id: 330, sira: 330, u: "Atatürkçü Düşünce Derneği Başkanı", i: "Cahit YAKA"},
  {id: 331, sira: 331, u: "Çağdaş Yaşamı Destekleme Derneği Başkanı", i: "Leyla URAL"},
  {id: 332, sira: 332, u: "Türk Ocakları Derneği Muğla Şube Başkanı", i: "Prof. Dr. Mustafa GÖKÇE"},
  {id: 333, sira: 333, u: "İlim Yayma Cemiyeti Başkanı", i: "Ayhan BALCI"},
  {id: 334, sira: 334, u: "Müstakil San. ve İşad. Der. Muğla Şube Başkanı (MÜSİAD)", i: "Nevzat AYKAÇ"},
  {id: 335, sira: 335, u: "Türkiye Beyazay Derneği Muğla Başkanı", i: "Pınar BOYACI"},
  {id: 336, sira: 336, u: "Türk Jinekoloji ve Obstetrik Derneği Muğla Şube Başkanı", i: "Eren AKBABA"},
  {id: 337, sira: 337, u: "Türkiye Yeşilay Cemiyeti Muğla Şube Başkanı", i: "Abdullah Şenol ŞENGÜR"},
  {id: 338, sira: 338, u: "Muğla Amatör Spor Kulüpleri Federasyonu Başkanı", i: "Mehmet TOP"},
  {id: 339, sira: 339, u: "Şehit Aileleri Yar. ve Dayanışma Drn. Başkanı", i: "Süleyman TAŞKESEN"},
  {id: 340, sira: 340, u: "Türkiye Harp Malulü Gaziler-Şehit Dul ve Yetim. Drn. Başkanı", i: "Celalettin EMRE"},
  {id: 341, sira: 341, u: "Muğla İli Muhtarlar Federasyon Başkanı", i: "Hayrettin AKAY"},
  {id: 342, sira: 342, u: "Muğla 48 Muhtarlar Federasyonu Başkanı", i: "Kadir GÜMÜŞ"},
  {id: 343, sira: 343, u: "Türkiye Emekli Astsubaylar Derneği Muğla Şube Başkanı", i: "Kemal ADAŞ"},
  {id: 344, sira: 344, u: "Türkiye Radyo Amatörleri Cemiyeti Muğla Şube Başkanı", i: "Murat Kaan KASAR"},
  {id: 345, sira: 345, u: "Türkiye Sakatlar Derneği Muğla Şube Başkanı", i: "Elif ŞENOL"},
  {id: 346, sira: 346, u: "Tema Vakfı İl Temsilcisi", i: "Murat Can SUNAR"},
  {id: 347, sira: 347, u: "Türkiye Gençlik Vakfı Muğla İl Temsilcisi", i: "Yusuf ESEN"},
  {id: 348, sira: 348, u: "Kadın ve Demokrasi Vakfı (KADEM) Muğla İl Temsilcisi", i: "Erizan YILMAZ"},
  {id: 349, sira: 349, u: "Muğla Genç İş İnsanları Derneği (MUGİAD)", i: "Murat ATACAN"}
];

export const HALL_CONFIGS: Record<string, HallConfig> = {
  yildiz: {
    name: "Gazi Mustafa Kemal AKM Yıldız Kenter Salonu",
    stage: { label: 'SAHNE', position: 'top', size: 'medium' },
    rows: [
      { row: 'A', seats: generateSeq(31) }, { row: 'B', seats: generateSeq(30) },
      { row: 'C', seats: generateSeq(31) }, { row: 'D', seats: generateSeq(30) },
      { row: 'E', seats: generateSeq(30) }, { row: 'F', seats: generateSeq(30) },
      { row: 'G', seats: generateSeq(30) }, { row: 'H', seats: generateSeq(30) },
      { row: 'I', seats: generateSeq(30) }, { row: 'J', seats: generateSeq(30) },
      { row: 'K', seats: generateSeq(30) }, { row: 'L', seats: generateSeq(30) },
      { row: 'M', seats: generateSeq(30) }, { row: 'N', seats: generateSeq(30) },
      { row: 'O', seats: generateSeq(30) }, { row: 'P', seats: generateSeq(19) },
      { row: 'R', seats: generateSeq(19) }, { row: 'S', seats: generateSeq(10) },
      { row: 'T', seats: generateSeq(26) }, { row: 'U', seats: generateSeq(26) },
      { row: 'V', seats: generateSeq(12) }
    ]
  },
  turkan: {
    name: "Türkan Saylan ÇYM Seminer Salonu",
    stage: { label: 'SAHNE', position: 'top', size: 'small' },
    rows: [
      { row: 'A', seats: generateSeq(17) }, { row: 'B', seats: generateSeq(16) },
      { row: 'C', seats: generateSeq(17) }, { row: 'D', seats: generateSeq(17) },
      { row: 'E', seats: generateSeq(17) }, { row: 'F', seats: generateSeq(17) },
      { row: 'G', seats: generateSeq(17) }, { row: 'H', seats: generateSeq(17) },
      { row: 'J', seats: generateSeq(17) }, { row: 'K', seats: generateSeq(17) },
      { row: 'L', seats: generateSeq(17) }, { row: 'M', seats: generateSeq(17) },
      { row: 'N', seats: generateSeq(16) }, { row: 'O', seats: generateSeq(17) },
      { row: 'P', seats: generateSeq(17) }, { row: 'R', seats: generateSeq(17) },
      { row: 'S', seats: generateSeq(17) }, { row: 'T', seats: generateSeq(17) }
    ]
  },
  msku: {
    name: "Muğla Sıtkı Koçman Üni. Atatürk Kültür Merkezi",
    stage: { label: 'ANA SAHNE', position: 'top', size: 'large' },
    rows: [
      { row: 'A', seats: [
          { number: "MS", type: "static" }, { number: "BSN", type: "static" }, 
          ...generateOdd(1, 7), { type: 'gap', size: 'large' }, 
          ...generateOdd(9, 23), ...generateEven(22, 10), 
          { type: 'gap', size: 'large' }, ...generateEven(8, 2), 
          { number: "BSN", type: "static" }, { number: "MS", type: "static" }
        ] 
      },
      { row: 'B', seats: [...generateOdd(1, 19), { type: 'gap', size: 'large' }, ...generateOdd(21, 35), ...generateEven(36, 22), { type: 'gap', size: 'large' }, ...generateEven(20, 2) ] },
      { row: 'C', seats: [...generateOdd(1, 21), { type: 'gap', size: 'large' }, ...generateOdd(23, 37), ...generateEven(38, 24), { type: 'gap', size: 'large' }, ...generateEven(22, 2)] },
      { row: 'D', seats: [...generateOdd(1, 23), { type: 'gap', size: 'large' }, ...generateOdd(25, 41), ...generateEven(40, 26), { type: 'gap', size: 'large' }, ...generateEven(24, 2)] },
      { row: 'E', seats: [...generateOdd(1, 27), { type: 'gap', size: 'large' }, ...generateOdd(29, 45), ...generateEven(46, 30), { type: 'gap', size: 'large' }, ...generateEven(28, 2)] },
      { row: 'F', seats: [...generateOdd(1, 27), { type: 'gap', size: 'large' }, ...generateOdd(29, 49), ...generateEven(50, 30), { type: 'gap', size: 'large' }, ...generateEven(28, 2)] },
      { row: 'G', seats: [...generateOdd(1, 27), { type: 'gap', size: 'large' }, ...generateOdd(29, 49), ...generateEven(50, 30), { type: 'gap', size: 'large' }, ...generateEven(28, 2)] },
      { row: 'H', seats: [...generateOdd(1, 27), { type: 'gap', size: 'large' }, ...generateOdd(29, 49), ...generateEven(50, 30), { type: 'gap', size: 'large' }, ...generateEven(28, 2)] },
      { row: 'I', seats: [...generateOdd(1, 27), { type: 'gap', size: 'large' }, ...generateOdd(29, 49), ...generateEven(50, 30), { type: 'gap', size: 'large' }, ...generateEven(28, 2)] },
      { row: 'J', seats: [...generateOdd(1, 23), { type: 'gap', size: 'small' }, ...generateOdd(25, 49), ...generateEven(50, 26), { type: 'gap', size: 'small' }, ...generateEven(24, 2)] },
      { row: 'S', seats: [...generateOdd(1, 25), { type: 'gap', size: 'large' }, ...generateEven(26, 2) ] },
      { row: 'T', seats: [...generateOdd(1, 17), { type: 'gap', size: 'small' }, ...generateOdd(19, 43), ...generateEven(44, 20), { type: 'gap', size: 'small' }, ...generateEven(18, 2)] }
    ]
  },
  bodrum: {
    name: "Bodrum Marmara Koleji Atatürk Kültür Merkezi",
    stage: { label: 'SAHNE', position: 'top', size: 'medium' },
    rows: [
      createBodrumRow('A', 7, 24, 6),
      createBodrumRow('B', 10, 24, 10),
      createBodrumRow('C', 11, 24, 11),
      createBodrumRow('D', 12, 24, 12),
      createBodrumRow('E', 12, 24, 12),
      createBodrumRow('F', 13, 24, 13),
      createBodrumRow('G', 13, 24, 13),
      createBodrumRow('H', 14, 24, 14),
      createBodrumRow('I', 14, 24, 14),
      createBodrumRow('İ', 15, 24, 15),
      createBodrumRow('J', 15, 24, 15),
      createBodrumRow('K', 16, 24, 16),
      createBodrumRow('L', 16, 10, 16),
      createBodrumRow('M', 9, 12, 9),
      createBodrumRow('N', 13, 0, 4),
      createBodrumRow('O', 12, 0, 11)
    ]
  }
};
